version: "3.8"

services:
  postgres:
    image: postgres
    container_name: florecultura_db
    restart: always
    # network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: florecultura
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
